spring.application.name=sifap-backend

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/sifap
spring.datasource.username=sifap
spring.datasource.password=sifap_local

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info
